export const quizLayout = {
  lg: [
    {
      i: "chat-component",
      x: 4,
      y: 0,
      w: 6,
      h: 12,
      minW: 6,
      maxW: 10,
      minH: 6,
      maxH: 12,
    },
    {
      i: "quiz-component",
      x: 12,
      y: 0,
      w: 8,
      h: 7,
      minW: 6,
      maxW: 12,
      minH: 7,
      maxH: 9,
    },
    {
      i: "first-to-answer",
      x: 12,
      y: 5,
      w: 8,
      h: 5,
      minW: 6,
      maxW: 12,
      minH: 5,
      maxH: 7,
    },
  ],
};
